config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
    get 'users/:id' => 'users#show'








  root "categories#index"
  resources :categories, only: [:show]
  resources :films, only: [:show, :index] do
    resources :comments, module: :films
    resources :ratings, module: :films
  end

  resources :reviews, except: [:index, :destroy] do
    resources :comments, module: :reviews
    resources :ratings, module: :reviews
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_films 
  has_many :films, through: :categories_films
  validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.take(6)
    if params[:search]
      @films = Film.search(params[:search]).order("created_at DESC")
    else
      @films = Film.all.order('created_at DESC')
    end
  end

  def show
    @category =  Category.find(params[:id])
  end

end

app/views/categories/index.html.erb
<h2 class="cat-heading">
<span>Hits for the weekend</span>
</h2>
<p class="text-lead">Discover new, inspiring movies at home.</p>

<ul class="bxslider">
  <li><img src="http://t0.gstatic.com/images?q=tbn:ANd9GcSb0Y7-yhSfUlu85u2RcdZArCg6UYCxkNsOducy4f-RMHD9fdkl" /></li>

  <li><img src=" http://t1.gstatic.com/images?q=tbn:ANd9GcTm52BWbxXmwOpfz5rmx0BNBj79kSQoGpYPq4TVt07Jel5En6aC" /></li>
  <li><img src="http://ia.media-imdb.com/images/M/MV5BMTc2NjMzOTE3Ml5BMl5BanBnXkFtZTcwMDE0OTc5Mw@@._V1__SX1219_SY519_.jpg" /></li>
   <li><img src="http://t1.gstatic.com/images?q=tbn:ANd9GcR-fLY3Z9Vn28UB-A3X_w0vjmkHcXG89HWwul5w6-sg3IonPXA_" /></li>
  <li><img src="http://t0.gstatic.com/images?q=tbn:ANd9GcQZKZtrlY3dnzsjBIGKR_b1QhkgZfM4-FIcH61uHnLQRR3WpNhk" /></li>
</ul>

<h2 class="cat-heading">
<span>Categories</span>
</h2>
<div class="row category-list">
  <% @categories.each do |category| %> 
    <div class="col-sm-2 ">
      <span class='category-position'><strong> <%= link_to "#{category.name}", category_path(category.id) %></strong></span><br />
      <% category.films.each do |film| %>
         <span> <%= link_to "#{film.title}", film_path(film.id) %> </span><br />
      <% end %>
    </div>
  <% end %> 
</div>

app/views/categories/show.html.erb
<h2 class="cat-heading">
Category: <%= @category.name %>
</h2>

<ul class="category-list">
  <% @category.films.each do |film| %>
  <li> <%= link_to "#{film.title}", film_path(film.id) %></li>
  <% end %>
</ul>