config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
    get 'users/:id' => 'users#show'








  root "categories#index"
  resources :categories, only: [:show]
  resources :films, only: [:show, :index] do
    resources :comments, module: :films
    resources :ratings, module: :films
  end

  resources :reviews, except: [:index, :destroy] do
    resources :comments, module: :reviews
    resources :ratings, module: :reviews
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/reviews/comments_controller.rb
class Reviews::CommentsController <CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Review.find(params[:review_id])
    end
end

app/controllers/reviews/ratings_controller.rb
class Reviews::RatingsController < RatingsController
  before_action :set_rateable

  private

    def set_rateable
      @rateable = Review.find(params[:review_id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @film = Film.find(params[:review][:film_id])
    @review = Review.new(review_params)
    @review.user = current_user
    if @review.save
      if request.xhr?
        render partial: "reviews/review", locals: {review: @review},layout: false

      else
        redirect_to action: 'show', controller:'films', id:params[:review][:film_id].to_i
      end
    else
      render action: 'show', controller:'films', id:params[:review][:film_id].to_i
    end
  end

  def edit
    @review = Review.find(params[:id])
    unless current_user == @review.user
      redirect_to(@review, notice: "You cannot edit this review!") and return
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(review_params)
      flash[:success] = "Review updated!"
      redirect_to @review
    else
      @errors = @review.errors.full_messages
      flash[:danger] = "You did not enter a valid reponse!"
      render 'reviews/edit'
    end
  end

  def show
    @review = Review.find(params[:id])
    @comment = @review.comments.new
    @film = Film.find_by(id: @review.film_id)
    @rating = Rating.new
  end

  private

    def review_params
      params.require(:review).permit(:review_title, :review_content, :recommend, :user_id, :film_id)
    end


end

app/views/reviews/_review.html.erb
<h3>Title: <%= link_to review.review_title.capitalize, review_path(review) %></h3>
<div>
  <strong>Film:</strong>
  <%= review.film.title %>
</div>
<div>
  <strong>Made By:</strong>
  <%= review.user.username %> -
  <% if review.user.trusted %>
    Trusted User!
  <% else %>
    Not Trusted!
  <% end %>
</div>
<div>
  <strong>Thoughts:</strong> <%= review.review_content %>
</div>
<div>
  <strong>Would You Recommend this Film?</strong>
    <% if review.recommend %>
      Yes!
    <% else %>
      Gosh No!
    <% end %>
</div>

app/views/reviews/_review_form.html.erb
<%= form_for review do |f| %>
  <%= f.hidden_field :film_id, value: @film.id %>

  <%= f.text_field :review_title, :placeholder => "Review Title", :class => "review-input"%><br />
  <%= f.text_area :review_content, :placeholder =>"Write your review here...", :class => "review-input" %> <br />
<div class="recommend-button">
  <%= f.label :Recommend? %>
  <%= f.check_box :recommend %><br />
</div>
  <%= f.submit "Create Review", class: "button-submit" %>
<% end %>

app/views/reviews/edit.html.erb
<main>
<div class='review-input recent-reviews-container'>

<%= form_for @review do |f| %>
  <div class="form-group">
    <div>
      <%= f.label :review_title, "Review Title",:class => "review-input" %>
    </div>
    <div>
      <%= f.text_field :review_title, value: @review.review_title %><br />
    </div>
    <div>
      <%= f.label :review_content, "Review Content", :class => "review-input"%>
    </div>
    <div>
      <%= f.text_area :review_content, value: @review.review_content %><br />
    </div>
    <div class="recommend-button">
      <%= f.label :Recommend? %>
      <%= f.check_box :recommend %><br />
    </div>
  </div>

  <%= f.submit "Edit Comment", class: "  button-submit" %>
<% end %>
</div>
</main>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>
  <div class="form-group">
    <%= f.text_field :review_title, class: "form-group", placeholder: "Review Title" %>
    <%= f.text_area :review_content, class: "form-group", placeholder: "Review Content" %>
  </div>

  <%= f.submit "Create Comment", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<main>
<div class="movie-comment-container">
<section class='review_rating'>
  <%= render partial: 'reviews/review', locals: { review: @review } %>

  Did you find this review useful?
  <%= render partial: 'ratings/review_new_rating', locals: { rateable: @review } %>
  <div class='review_useful'>
    <%= render partial: 'ratings/review_usefule_rating', locals: { rateable: @review } %>
  </div>
</section>

<div>
  <% if current_user == @review.user %>
    <%= link_to "Edit", edit_review_path(@review) %>   |
  <% end %>

  <%= link_to "Back", film_path(@film) %>
</div>

<%= render partial: "comments/comments", locals: { commented_on: @review } %>

<div class="form-container">
  <%= render partial: "comments/form", locals: { commented_on: @review } %>
</div>
</div>
</main>